// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBf9UOI3PHKSHW0E4i9qoSHOtIpmHBccY',
    appId: '1:889940338135:web:79e5a6ce84bbd7cfefd792',
    messagingSenderId: '889940338135',
    projectId: 'hourlynotes',
    authDomain: 'hourlynotes.firebaseapp.com',
    storageBucket: 'hourlynotes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfiE-HFceAPVOBT2vEqkEnCQG6RpWyo8A',
    appId: '1:889940338135:android:0153f1fb7322ba69efd792',
    messagingSenderId: '889940338135',
    projectId: 'hourlynotes',
    storageBucket: 'hourlynotes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj3wCJmFJL1xBxMYDOcH_A3kXc_3QwmT8',
    appId: '1:889940338135:ios:4e70ff622b0288bcefd792',
    messagingSenderId: '889940338135',
    projectId: 'hourlynotes',
    storageBucket: 'hourlynotes.firebasestorage.app',
    iosBundleId: 'com.dokahub.hourlynotes',
  );
}
